### ISSUE TITLE
Link to spreadsheet containing glossary is not accessible

### ISSUE THREAD

**Issue by ehpor** [chen-pin/ebs#2]
@chen-pin See https://github.com/chen-pin/ebs/blob/fa02f31e708e9636303e1d10986f490229268d05/doc/Post-Processing%20Factor.ipynb#L40.

The Google Drive link to this spreadsheet is only accessible for JPL, not outside institutes.

![image](https://github.com/chen-pin/ebs/assets/38925765/297760a4-8cb8-488a-80e6-164749b6a6d3)

**Comment by chen-pin** [comment]
Fixed with the last commits 71ed9 and 1daf5
